### ISSUE TITLE
Search issues - 22.Jan call

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#114]
Topics discussed on the [dataset name search](https://dev.col.plus/dataset/1027/names?facet=rank&facet=issue&facet=status&limit=50&offset=0) to be changed or further clarified:

 - 2 search views: generic & duplicate review
 - hide issues by severity (error, warning, info) & group (taxon, name, etc)
   - hide issues from both filters and search results
 - color issues by severity (red, orange, green)
 - show name properties as columns? Unresolved question, could by a lot. See [Name class](https://sp2000.github.io/colplus/api/api.html#model-Name) for full list of properties.
 - highlight search query

Duplicate review view:
 - color duplicates the same
 - apply decision, ie. status in bulk

**Comment by thomasstjerne** [comment]
Maybe we should link duplicate pairs in some way.
In order to easily color a duplicate set, they should be linked to each other somehow.
Also, I think there could be cases were simple sorting would not necessarily place duplicates together. E.g. if one has a subgenus between Genus and epithet and the other doesn´t ?

**Comment by mdoering** [comment]
Actual duplicates should have the same indexNameId. Not sure how far that gets us
