### ISSUE TITLE
Show broken sectors

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-frontend#148]
We also need to list sectors (and also ultimately decisions) which have broken references to taxa in source datasets (subject) or the draft catalgoue itself (target). These need to be fixed by the user or be updated semiautomatically with a suggested replacement taxonID.

The API allows to retrieve such broken sectors with required parameter datasetKey due to db partitioning:
/sector/broken?datasetKey=X

This default to list broken sectors for the subject/sources, but the optional param `target=true`can be given to query for broken attachments to the CoL

**Comment by thomasstjerne** [comment]
awaiting https://github.com/Sp2000/colplus-backend/issues/291

**Comment by thomasstjerne** [comment]
Get all datasets that contributes to CoL, the call /sector/broken?datasetKey=X forEach and concat results

**Comment by mdoering** [comment]
nice, a few further suggestions:

 - show sector mode
 - indicate whether target or subject is broken
 - provide a way to fix it. As a start a simple rematch button on each sector that calls a new rematch API method I can quickly expose? That method could also update all sectors from a dataset, but for now we stick to that sector list view.
 - link to name search instead of logs for the given dataset in case of broken subjects, and to draft (key=3) name search if the target is broken

**Comment by mdoering** [comment]
Exposing new sector and decision rematch method shortly
which returns the object in question after rematching.

`POST /sector/{key}/rematch`
`POST /decision/{key}/rematch`

**Comment by mdoering** [comment]
@thomasstjerne rematch methods available on dev now

**Comment by mdoering** [comment]
Are these changes deployed yet?

- show sector mode
- indicate whether target or subject is broken
- provide a rematch button
- link to name search instead of logs

**Comment by thomasstjerne** [comment]
On dev yes, on its way to prod now

**Comment by thomasstjerne** [comment]
https://www.col.plus/sector/broken
