### ISSUE TITLE
Categorize references on info pages and link vernacular names

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#177]
References on a taxon info page should indicate what they are about. Individual vernacular names and distributions can link to a specific reference.

https://api.col.plus/dataset/1010/taxon/10312/info

http://www.catalogueoflife.org/col/details/species/id/a390e77db99c49c52a4f173428c89a10

We could also tag every reference with the 4 possible topics: name, taxon, vernacular, distribution

**Comment by thomasstjerne** [comment]
> We could also tag every reference with the 4 possible topics: name, taxon, vernacular, distribution
Yes please, that would make it possible

**Comment by mdoering** [comment]
Client or serverside tagging? In any case we also need direct links like footnotes from every entity that refers to a reference.

**Comment by thomasstjerne** [comment]
If we want to use the CSL presentation, it will be possible to create 4 sublists of references, one for each topic, but If a CSL format using a numbered list is chosen, each of these lists will start at 1.
Otherwise we should choose only unnumbered formats and then display each reference as a list of one item. Then I could possibly add tags after each ref somehow - but this will also break the ordering rules of the selected CSL style. 

I think I will make it optional to see either the default citation with tags/links OR choose CSL formatting.

So the client should look for:
- taxon.referenceId
- taxon.name.referenceId
- distributions[i].referenceId
- vernacularNames[i].referenceId

?

**Comment by mdoering** [comment]
I would prefer a classic single list at the bottom, the same reference can be used from different places.

I need to update the db schema, but the reference links should still be fine: https://github.com/Sp2000/colplus/blob/master/docs/dbschema.pdf
A TaxonInfo contains the following reference links:
 - taxonReferences
 - taxon.speciesEstimateReferenceId
 - taxon.name.publishedInId
 - distributions[i].referenceId
 - vernacularNames[i].referenceId
 - media[i].referenceId
 - descriptions[i].referenceId

 - taxon.accordingTo will probably become a reference very soon: https://github.com/Sp2000/colplus-backend/issues/276

The TaxonInfo object does not contain name relations which also have a `publishedInId` which refers to a reference. Should we include them in the info object so all distinct references are there?

**Comment by mdoering** [comment]
Vernacular and synonym references show fine now (can the popup deal with multiple refs?). I could not find examples for distributions, media or descriptions.
But I still can't find 
 - [ ] taxonomic references (taxon.referenceIds)
for https://dev.col.plus/dataset/1010/taxon/164686
https://api-dev.col.plus/dataset/1010/taxon/164686/info

 - [ ] distributions
for https://dev.col.plus/dataset/1700/taxon/1001b

 - [ ] media and descriptions which are to be done in #268 269

Would it not be a good idea to have all references listed at the bottom and link to them instead of a popup? Just like a classic bibliography in e.g. wikipedia so you can screen all uses sources.
