### ISSUE TITLE
Add a drop all data button to the admin tab

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#264]
Being able to drop all synced data from the [admin page](https://www.col.plus/admin) to work with a few sectors at a time would be really useful, especially during testing but it will also be useful for our normal workflow when we just want to run conversion on a small number of datasets for testing.

**Comment by mdoering** [comment]
I was thinking about the same to test the conversion. 
I am not sure if it is a good idea to do so in production though as the system was deliberately designed to do incremental changes. You cannot detect duplicates across sectors otherwise. 

It would have been implemented a lot simpler and faster if we only ever did full assemblies from scratch. Nevertheless its a useful feature for testing on dev even while we have a stable prod environment

**Comment by mdoering** [comment]
I am closing this as its only useful for testing and we are close to get into data maintenance mode
