### ISSUE TITLE
Metadata: value "On demand" is missing in the field Import Frequency

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-frontend#335]
Value "On demand" is necessary for cases where GSD custodian updates data irregularly, following the progress of his project (for example, twice in 2012, once in 2015, and next time in 2018). Frequencies of updates might be different, depending on funding and priorities of the custodian. The case does not covered by existing values "once", "never" or "yearly".

**Comment by yroskov** [comment]
Thomas explained that this field is for GSDs with automated updates only. In this case, please, 
1) change field name in the interface as **Automated Import Frequency** 
2) set up default value **Never** (or **Once**?) for all GSDs which have no automated pipes

**Comment by mdoering** [comment]
Yes, its for the continous importing only and Never is the right one. 
Unless data has changed it doesnt hurt to use WEEKLY though, because the import attempt will be stopped when the data file has not changed. And as we take it from github in those not automated cases it will stay the same until Geoff updates it "on demand". 

I don't see the need for changing any settings, but if you prefer to only do manual imports please change them in the metadata once we go into production
