### ISSUE TITLE
Use only gsdShortName (Alias) in all lists and reports

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-frontend#347]
Please use only gsd**Short**Name (Alias)* in all lists and reports in CoL+. 

(However, please, keep Search GSD option by any word in Short and Full names (as it is implemented now), and please add option to search for gsdID from the same search box (i.e. search for ShortName (e.g. "3i Aucheno"), FullName ("World Au"), gsdID ("1189"); and deliver final report with a list of short names only).

Reports which I can spot:
Dataset – Search: https://www.col.plus/dataset?limit=20&offset=0 
Dataset – Issues (gsdShortName is already implemented).

Catalogue – Assembly (gsdName in right frame): https://www.col.plus/assembly?datasetKey=1166 
Catalogue – Broken Sectors: https://www.col.plus/sector/broken 

Imports – Running: https://www.col.plus/imports/running?limit=10&offset=0&state=waiting&state=downloading&state=processing&state=inserting&state=indexing&state=building%20metrics
Imports – Finished: https://www.col.plus/imports/finished?limit=10&offset=0&state=unchanged&state=finished&state=canceled&state=failed

etc.

**Comment by thomasstjerne** [comment]
As the "alias" field is not mandatory and often not filled, this has been implemented in different ways, depending on highlighting, search and sort.

Where there is no complication (sorting, highlighting), I have set it to use alias if exists, with fallback to title when there is no alias.

Dataset – Search: https://www.col.plus/dataset?limit=20&offset=0 - here you have to select to hide the title. Alias is not yet sortable awaiting https://github.com/Sp2000/colplus-backend/issues/485

Sectortables (broken and dataset): here I have replaced the dataset title with dataset alias because we have search and highlighting in the table. You will see blanks where the alias is missing.

**Comment by mdoering** [comment]
Would it be useful to auto generate an alias based on the title if its missing?
we could abbreviate the title, create an acronym from first letters or even try to guarantee a unique short name based on the title

**Comment by yroskov** [comment]
gsdShortName (or "alias" as you decide to call it) relates to branding of GSD (as well as GSD logo). Only GSD can decide what are its full and short names. You cannot generate it automatically.

**Comment by yroskov** [comment]
gsdShortName was mandatory field in CoL.

**Comment by mdoering** [comment]
As we now have many more datasets then pure "GSD"s we cannot mandate the alias.
If autogenerated you surely can manually manage it and we will clearly use the one provided by the dataset - if it was provided. It's just a way to avoid not having any alias at all, the last resort

**Comment by yroskov** [comment]
Use of FullName only is not a way. Have a look on full names of 90% checklists in WoRMS, they have a difference in one word only. Management of CoL GSDs without ShortNames become very difficult.
