### ISSUE TITLE
Treat catalogues just as datasets

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#362]
As we will have multiple catalogues not just the draft we need to think about how to switch between them and visualize them.

My gut feeling is that we treat them just as datasets, but offer specific submenu items depending on a datasets type. If the dataset is of type catalogue we can show the assembly, sector sync, broken sectors, workbench, duplicates. If its of type external or uploaded we will have import metrics instead. It might be a good time to review all menu items and maybe collapse a few of them, e.g. workbench & name search. Those two should probably mostly be the same and only differ if the user is allowed to apply decisions?

Also for released catalogues we need to find a way to make sure they are immutable:
https://github.com/Sp2000/colplus-backend/issues/505

**Comment by gdower** [comment]
@mdoering, I'm wondering about the placement of /decision in the API, because if catalogues are treated as datasets, then other projects might want to have their own independent decisions, and also the decisions should probably be frozen with the released catalogues as a record of what was decided upon for that catalogue edition. I think it might make sense to put decisions here:

https://api.col.plus/assembly/3/decisions 

Eventually, I think we should also push the decisions to a GitHub repo (maybe colplus-repo:/decisions?) to have a versioning history. Possibly we should push the decisions back to the data repos, too, with subdirectory for each project?

https://github.com/Sp2000/data-unit-tests/blob/master/decisions/colplus/decisions.tsv
https://github.com/Sp2000/data-unit-tests/blob/master/decisions/gbif/decisions.tsv

**Comment by mdoering** [comment]
@gdower with that big refactoring last week decisions, estimates and sectors are all scoped by a datasetKey wich refers to the catalogue. so they are kept as they are when the catalogue was released. 

But all these 3 objects do still have a globally unique key and thats why they continue to live as global CRUD resources. I wondered if we should still place them under assembly or rather dataset in the API, but decided against it. 

Makes sense?

**Comment by mdoering** [comment]
Regarding github I dont think we should require or assume a source is hosted in GH. There will be many outside. It is a convention and hopefully a convenience for you to do so. Not dure about automated worms or itis datasets. But at least when we build the provisional catalogue we deal with external dwca datasets outside of GH
