### ISSUE TITLE
400 Unknown term parameter cold:relatedNameUsageID

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#390]
verbatim browser fails:

https://www.col.plus/dataset/2000/verbatim?type=dwc:Taxon&type=dwc:VernacularName&type=dwc:Description&type=dwc:Distribution&type=dwc:Multimedia&type=dwc:Reference&type=cold:NameRelations&dwc:acceptedNameUsageID=urn:lsid:ipni.org:names:168230-1&dwc:originalNameUsageID=urn:lsid:ipni.org:names:168230-1&dwca:id=urn:lsid:ipni.org:names:168230-1&dwca:id=urn:lsid:ipni.org:names:168230-1&dwca:id=urn:lsid:ipni.org:names:168230-1&dwca:id=urn:lsid:ipni.org:names:168230-1&dwca:id=urn:lsid:ipni.org:names:168230-1&dwca:id=urn:lsid:ipni.org:names:168230-1&cold:relatedNameUsageID=urn:lsid:ipni.org:names:168230-1&termOp=OR

**Comment by thomasstjerne** [comment]
Is it because "cold:NameRelations.cold:relatedNameUsageID" in [terms.json](https://github.com/Sp2000/colplus-frontend/blob/master/public/terms.json) should be renamed to
"cold:NameRel.cold:relatedNameUsageID" ?

Its the backend complaining about the parameter name, can I see the allowed parameters somewhere?
