### ISSUE TITLE
Need to reload app when visiting the domain

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#468]
When going to https://data.catalogue.life or https://data.dev.catalogue.life I always get a blank screen and need to reload the page to see anything.

**Comment by thomasstjerne** [comment]
I cant reproduce this now, and I tested with several browsers.
It should be fixed by https://github.com/Sp2000/colplus-frontend/commit/f0148416de2dccb74c7693e14849085562fe0d32#diff-1fdf421c05c1140f6d71444ea2b27638
However, for clients having the old version (with the service worker) it would only be fixed on the second reload. Ill leave this open, but it need to be re-tested

**Comment by mdoering** [comment]
gone for me
